project_id = "vzxviibhpbzuiucgodiw"

[functions.send-email]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.import-csv]
verify_jwt = true

[functions.clear-hotel-data]
verify_jwt = true